name: advent_of_code
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.15.0-178.1.beta <3.0.0'


dev_dependencies:
  lints: ^1.0.0
dependencies: 
  args: ^2.3.0
