name: advent_of_code
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.14.0 <3.0.0'


dev_dependencies:
  lints: ^1.0.0
  test: ^1.19.5
dependencies: 
  args: ^2.3.0
  quiver: ^3.0.1+1
